name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
      - develop
    types:
      - synchronize
      - opened

jobs:
  test:
    name: Run Tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Run tests
        run: pnpm test:run
        env:
          # Example of using GitHub secrets
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # API_KEY: ${{ secrets.API_KEY }}
          NODE_ENV: test

      - name: Upload test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results (Node ${{ matrix.node-version }})
          path: test-results.xml
          reporter: java-junit

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: test-results.xml
          retention-days: 30

  flaky-tests:
    name: Run Flaky Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run flaky tests
        run: |
          echo "Running intentionally flaky tests..."
          pnpm test:run src/flaky-tests.test.ts || echo "Flaky tests failed (this is expected)"
          echo "Flaky tests completed"
        continue-on-error: true
